spring.application.name=e-wastemanagement
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/wastemanagement
spring.datasource.username=root
spring.datasource.password=Saurabh9730
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhandarisaurabh500@gmail.com
spring.mail.password=xvfkvjigevfzjzat
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


